#!/usr/bin/env perl
use strict;
use warnings;
# Without this the em dash in the generated banner is treated as raw bytes and
# then re-encoded on the way out, landing in the HTML as mojibake.
use utf8;
use JSON::PP;
use File::Basename qw(dirname);
use File::Spec;

# Inlines the plugin's agent definitions and house rules into the two HTML pages
# that talk to the Claude API directly, so they send exactly what the plugin
# sends. Re-run after editing anything in wp-content/plugins/eduai-assistant/agents/.
#
#     perl scripts/sync-agents.pl
#
# Each target carries a marked block; everything between the markers is replaced:
#
#     /* AGENTS:START */  ...generated...  /* AGENTS:END */
#
# Idempotent — running it twice produces the same file. Perl is used rather than
# node or php because it is the one runtime Git for Windows always installs.

my $root = File::Spec->rel2abs(File::Spec->catdir(dirname(__FILE__), File::Spec->updir));
my $agents_dir = "$root/wp-content/plugins/eduai-assistant/agents";

my @targets = (
    "$root/design/preview.html",
    "$root/tools/agent-test.html",
);

# Mirrors EduAI_Agents::resolve_model(). A vendor family name is read as a
# capability tier, so the same agent files run against Anthropic or Groq; the
# pages map tier to a concrete model id once they know which key was pasted.
my %alias = (
    opus   => 'strongest',
    sonnet => 'balanced',
    haiku  => 'fast',
);

sub slurp {
    my ($path) = @_;
    open(my $fh, '<:encoding(UTF-8)', $path) or die "$path: $!\n";
    my $raw = do { local $/; <$fh> };
    close $fh;
    $raw =~ s/\r\n|\r/\n/g;
    return $raw;
}

sub resolve_model {
    my ($v) = @_;
    return undef unless defined $v;
    $v = lc $v;
    $v =~ s/^\s+|\s+$//g;
    return undef if $v eq '' || $v eq 'inherit' || $v eq 'default';
    return $alias{$v} if exists $alias{$v};
    # A tier named directly, or a literal model id pinned to one provider.
    return $v;
}

opendir(my $dh, $agents_dir) or die "$agents_dir: $!\n";
my @files = sort grep { /\.md$/ } readdir($dh);
closedir $dh;

my (@agents, $house);

for my $file (@files) {
    my $raw = slurp("$agents_dir/$file");

    # A leading underscore marks a shared fragment, not an agent.
    if ($file =~ /^_/) {
        next unless $file eq '_house-rules.md';
        $house = $raw;
        $house =~ s/\A---\n.*?\n---\n?//s;
        $house =~ s/<!--.*?-->//gs;
        $house =~ s/^\s+|\s+$//g;
        next;
    }

    my (%meta, $body);
    $body = $raw;

    if ($raw =~ /\A---\n(.*?)\n---\n?(.*)\z/s) {
        $body = $2;
        for my $line (split /\n/, $1) {
            $line =~ s/^\s+|\s+$//g;
            next unless $line =~ /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/;
            my ($k, $v) = (lc $1, $2);
            $v =~ s/^["'\s]+|["'\s]+$//g;
            $meta{$k} = $v;
        }
    }

    # Comments are notes for whoever edits the file, never instructions for the
    # model, so they must not reach the API.
    $body =~ s/<!--.*?-->//gs;
    $body =~ s/^\s+|\s+$//g;
    next unless length $body;

    my $id = $meta{name} // ($file =~ s/\.md$//r);

    push @agents, {
        id          => $id,
        label       => $meta{label} // ucfirst($id =~ s/[-_]/ /gr),
        description => $meta{description} // '',
        temperature => (defined $meta{temperature} && $meta{temperature} =~ /^-?[\d.]+$/)
                       ? $meta{temperature} + 0 : undef,
        model       => resolve_model($meta{model}),
        order       => (defined $meta{order} && $meta{order} =~ /^-?\d+$/) ? $meta{order} + 0 : 50,
        prompt      => $body,
    };
}

die "no agents found in $agents_dir\n" unless @agents;
die "no house rules found in $agents_dir/_house-rules.md\n" unless defined $house && length $house;

@agents = sort { $a->{order} <=> $b->{order} or $a->{label} cmp $b->{label} } @agents;

my $json = JSON::PP->new->canonical->pretty;
my %by_id = map { $_->{id} => $_ } @agents;

my $block = "/* AGENTS:START */\n"
    . "/* Generated by scripts/sync-agents.pl from the plugin's agents/*.md — do not edit by hand. */\n"
    . 'var LIVE_AGENTS=' . $json->encode(\%by_id) . ";\n"
    . 'var AGENTS_LIST=' . $json->encode(\@agents) . ";\n"
    . 'var HOUSE_RULES=' . $json->allow_nonref->encode($house) . ";\n"
    . "/* AGENTS:END */";

for my $target (@targets) {
    unless (-f $target) {
        warn "skipped (missing): $target\n";
        next;
    }

    my $html = slurp($target);

    unless ($html =~ m{/\*\s*AGENTS:START\s*\*/.*?/\*\s*AGENTS:END\s*\*/}s) {
        warn "skipped (no AGENTS markers): $target\n";
        next;
    }

    $html =~ s{/\*\s*AGENTS:START\s*\*/.*?/\*\s*AGENTS:END\s*\*/}{$block}s;

    open(my $out, '>:encoding(UTF-8)', $target) or die "$target: $!\n";
    print $out $html;
    close $out;

    printf "updated %s\n", $target;
}

# Keep the working copy at the project root in step with the shippable source,
# carrying over whatever API_KEY has been pasted into it. That is what lets the
# key live only on this machine: design/preview.html stays clean enough to ship,
# and refreshing the root copy never wipes the key out of it.
my $src = "$root/design/preview.html";
my $dst = "$root/preview.html";

if ( -f $src && -f $dst ) {
    my ($key) = slurp($dst) =~ /^var API_KEY = '([^']*)';/m;
    my $copy = slurp($src);

    if ( defined $key && length $key ) {
        $copy =~ s/^var API_KEY = '[^']*';/var API_KEY = '$key';/m;
    }

    open( my $fh, '>:encoding(UTF-8)', $dst ) or die "$dst: $!\n";
    print $fh $copy;
    close $fh;

    printf "refreshed %s (API_KEY carried over: %s)\n",
        $dst, ( defined $key && length $key ) ? 'yes' : 'none set';
}

printf "\n%d agents, %d chars of house rules\n", scalar(@agents), length($house);
printf "  %-22s %-20s temp %s\n",
    $_->{id}, $_->{model} // "(site default tier)",
    defined $_->{temperature} ? $_->{temperature} : '(site default)'
    for @agents;
